import Head from 'next/head';
import styles from '../styles/Home.module.css';

// We need to use top level await on these modules as they are async.
// This is actually what let's module federation work with NextJS
const Nav = (await import('common/Nav')).default;
const add = (await import('common/add')).default;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App B</title>
        <meta name="description" content="Generated by create next app B" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <h2>
        {`Adding 2 and 3 ==>`} {add(2, 3)}
      </h2>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to App B</h1>
      </main>
    </div>
  );
}
